# BUILD LOCATION OF SOFTWARES USED FOR THE SIMULATIONS
export TARGETDIR="${HOME}/apps"
export PROJNAME="project_nebula"
export PROJDIR="${PIPELINEDIR}/${PROJNAME}"
export COMPUTER="my_comp"

# LOCATION OF BASIC APPS TO BE INSTALLED AND
# WHETHER OF THEM TO BE INSTALLED
export INSTALL_GEANT4="FALSE"
export GEANT4_ROOT=""${TARGETDIR}/geant4""
export INSTALL_ROOT="FALSE"
export ROOT_ROOT=""${TARGETDIR}/ROOT""
export INSTALL_ANAROOT="TRUE"
export ANAROOT_ROOT=""${TARGETDIR}/AnaROOT""